[package]
name = "minimal_timeseries"
version = "0.1.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]

[dependencies]
chrono = "0.4.6"
log = "0.4.5"
fern = { version = "0.5.6", features = ["colored"] }
byteorder = "1.2.6"
ndarray = "0.12.0"
num-traits = "0.2.6"

#used for tests only
fxhash = "0.2.1"