[package]
name = "byteseries"
version = "0.1.1"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
log = "0.4.5"
fern = { version = "0.5.6", features = ["colored"] }
byteorder = "1.2.6"
ndarray = "0.12.0"
num-traits = "0.2.6"

#used for tests only
fxhash = "0.2.1"