[package]
name = "byteseries"
version = "0.3.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
thiserror = "1.0"
log = "0.4.5"
byteorder = "1.2.6"
num-traits = "0.2.12"

[dev-dependencies]
fxhash = "0.2.1"
fern = { version = "0.6", features = ["colored"] }
float_eq = "0.5"
